Add missing imports (#1298)
Without these the build fails with:

Assets/Script/Audio/Bass/BassAudioManager.cs(161,21): error CS0103: The name 'ToastManager' does not exist in the current context
Assets/Script/Helpers/FileExplorerHelper.cs(150,39): error CS0103: The name 'Path' does not exist in the current context